version: '3'
services:
  api:
    image: dauid64/assist-lamfo
    build:
      context: .
    env_file:
      - ./docker_env_files/.env
    ports:
      - "3000:3000"
  # nginx:
  #   image: dauid64/nginx
  #   build: 
  #     context: ./nginx
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - api