version: '3'
services:
  api:
    image: dauid64/assist-lamfo
    environment:
      OPENAI_API_KEY: "sk-proj-0mBmyCpFH0L3hWajdzHwT3BlbkFJX3w0GduftLHHbypGYFAF"
      RUST_LOG: "assist_lamfo=info"
    build:
      context: .
    ports:
      - "8000:8000"
