version: '3'
services:
  api:
    image: dauid64/assist-lamfo
    build:
      context: .
    env_file:
      - ./docker_env_files/.env
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - api