version: '3'
services:
  api:
    image: dauid64/lamfo-gpt
    build:
      context: .
    env_file:
      - ./docker_env/.env
    ports:
      - "3000:3000"
    depends_on:
      - db
      - qdrant
    restart: "on-failure"
  db:
    image: postgres:16
    env_file:
      - ./docker_env/.env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./docker_env/.env
    ports:
      - "15432:80"
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_data:/qdrant/storage:z