version: '3'
services:
  api:
    image: dauid64/assist-lamfo
    build:
      context: .
    env_file:
      - ./docker_env_files/.env
    ports:
      - "8000:8000"
  nginx:
    image: dauid64/nginx
    build: 
      context: ./nginx
    ports:
      - "8080:8080"
    depends_on:
      - api