CREATE TABLE "message" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

    session_id varchar(128) NOT NULL,
    content varchar(256) NOT NULL,
    typed_role varchar(50) NOT NULL
);